import { Bell, CheckCircle, Home, KeyRound, Lock, Palette, ShieldCheck, Trash2, UserRound } from "lucide-react";
import { useState } from "react";
import { Badge, Button, Card, Input, Modal } from "../../../components/ui";

function Toggle({ enabled, onChange, label, description }) {
  return <div className="flex items-center justify-between gap-4"><div><p className="font-semibold">{label}</p><p className="mt-1 text-sm leading-6 text-hive-muted">{description}</p></div><button type="button" role="switch" aria-checked={enabled} onClick={() => onChange(!enabled)} className={`relative h-7 w-12 shrink-0 rounded-full transition ${enabled ? "bg-hive-terracotta" : "bg-hive-border"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition ${enabled ? "left-6" : "left-1"}`} /></button></div>;
}

function SettingsPage() {
  const [profile, setProfile] = useState({ name: "Aisha Martin", email: "aisha@maplehouse.ca", avatar: "AM" });
  const [notifications, setNotifications] = useState({ chores: true, messages: true, birthdays: true });
  const [theme, setTheme] = useState("Warm HomeHive");
  const [privacy, setPrivacy] = useState("Hive members can see my profile");
  const [modal, setModal] = useState("");
  const [notice, setNotice] = useState("");
  const [password, setPassword] = useState({ current: "", next: "" });
  const avatarOptions = ["AM", "AS", "AI", "AH"];
  const saveProfile = () => setNotice("Your profile changes are saved locally for this prototype.");
  const changePassword = () => { if (!password.current || password.next.length < 8) return; setModal(""); setPassword({ current: "", next: "" }); setNotice("Password update saved as a UI-only change."); };

  return <main className="min-h-screen bg-hive-canvas px-4 py-6 sm:px-6 lg:px-10 lg:py-10"><div className="mx-auto max-w-5xl"><header><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.16em] text-hive-terracotta"><UserRound size={16} /> Your space</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Profile & settings</h1><p className="mt-3 max-w-xl text-hive-muted">Manage your details, preferences, and place in Maple House.</p></header>
    {notice && <div className="mt-6 flex items-center justify-between gap-3 rounded-hive-md bg-hive-sage-soft px-4 py-3 text-sm text-hive-sage"><span>{notice}</span><button type="button" onClick={() => setNotice("")} className="font-bold">Dismiss</button></div>}
    <div className="mt-7 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><Card className="p-6 sm:p-8"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-hive-md bg-hive-rose-soft text-hive-terracotta"><UserRound size={20} /></div><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Profile</p><h2 className="mt-1 text-2xl font-bold">About you</h2></div></div><div className="mt-7 flex items-center gap-5"><div className="flex h-18 w-18 items-center justify-center rounded-full bg-hive-terracotta text-xl font-bold text-white">{profile.avatar}</div><div><p className="font-semibold">Choose an avatar</p><div className="mt-3 flex gap-2">{avatarOptions.map((avatar, index) => <button key={avatar} type="button" onClick={() => setProfile({ ...profile, avatar })} className={`flex h-9 w-9 items-center justify-center rounded-full text-xs font-bold transition ${profile.avatar === avatar ? "bg-hive-terracotta text-white ring-4 ring-hive-rose-soft" : index % 2 ? "bg-hive-honey text-hive-ink" : "bg-hive-sage-soft text-hive-sage"}`}>{avatar}</button>)}</div></div></div><div className="mt-8 space-y-5"><Input label="Name" value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value })} /><Input label="Email address" type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} /><Button onClick={saveProfile}>Save profile</Button></div></Card>
      <Card className="overflow-hidden bg-hive-ink-soft p-6 text-white sm:p-8"><div className="flex h-11 w-11 items-center justify-center rounded-hive-md bg-hive-honey text-hive-ink"><ShieldCheck size={21} /></div><p className="mt-6 text-sm font-bold uppercase tracking-[0.16em] text-hive-honey">Account trust</p><h2 className="mt-2 text-2xl font-bold">Your household space stays yours.</h2><p className="mt-3 leading-7 text-white/65">HomeHive makes sensitive choices clear before they happen. Payment and deletion actions are never hidden behind a tap.</p><div className="mt-7 space-y-3 border-t border-white/10 pt-5 text-sm"><p className="flex items-center gap-2"><CheckCircle size={16} className="text-hive-honey" /> Email connected</p><p className="flex items-center gap-2"><CheckCircle size={16} className="text-hive-honey" /> Maple House member</p></div></Card></div>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-6 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-hive-md bg-hive-sage-soft text-hive-sage"><Bell size={20} /></div><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Preferences</p><h2 className="mt-1 text-2xl font-bold">How HomeHive reaches you</h2></div></div><div className="mt-7 space-y-6"><Toggle enabled={notifications.chores} onChange={(value) => setNotifications({ ...notifications, chores: value })} label="Chore reminders" description="Due dates and shared rotation nudges." /><Toggle enabled={notifications.messages} onChange={(value) => setNotifications({ ...notifications, messages: value })} label="Chat messages" description="New messages and important announcements." /><Toggle enabled={notifications.birthdays} onChange={(value) => setNotifications({ ...notifications, birthdays: value })} label="Birthday alerts" description="A gentle reminder before someone’s day." /></div></Card>
      <Card className="p-6 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-hive-md bg-hive-rose-soft text-hive-terracotta"><Palette size={20} /></div><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Appearance & privacy</p><h2 className="mt-1 text-2xl font-bold">Your comfort settings</h2></div></div><div className="mt-7 space-y-5"><label className="block text-sm font-semibold">Theme<select value={theme} onChange={(event) => setTheme(event.target.value)} className="mt-2 min-h-12 w-full rounded-hive-md border border-hive-border bg-hive-surface px-3 font-normal outline-none focus:border-hive-terracotta focus:ring-4 focus:ring-[var(--hh-focus-ring)]"><option>Warm HomeHive</option><option>System default</option><option>Soft night</option></select></label><label className="block text-sm font-semibold">Privacy<select value={privacy} onChange={(event) => setPrivacy(event.target.value)} className="mt-2 min-h-12 w-full rounded-hive-md border border-hive-border bg-hive-surface px-3 font-normal outline-none focus:border-hive-terracotta focus:ring-4 focus:ring-[var(--hh-focus-ring)]"><option>Hive members can see my profile</option><option>Show only my name</option><option>Keep profile private</option></select></label><p className="rounded-hive-md bg-hive-canvas p-4 text-sm leading-6 text-hive-muted">Theme selections are saved as a UI preference for now. Your privacy choice is always visible here.</p></div></Card></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-6 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-hive-md bg-hive-sage-soft text-hive-sage"><Home size={20} /></div><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">HomeHive</p><h2 className="mt-1 text-2xl font-bold">My Hive</h2></div></div><div className="mt-7 rounded-hive-lg bg-hive-canvas p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-bold">Maple House</p><p className="mt-1 text-sm text-hive-muted">4 members · You&apos;re the owner</p></div><Badge variant="success">Active</Badge></div><div className="mt-5 flex gap-3"><a href="/members" className="inline-flex min-h-10 items-center justify-center rounded-hive-sm border border-hive-border bg-hive-surface px-3 text-sm font-semibold hover:border-hive-terracotta">Manage members</a><Button variant="ghost" className="text-red-600 hover:bg-red-50 hover:text-red-700" onClick={() => setModal("leave")}>Leave Hive</Button></div></div></Card>
      <Card className="p-6 sm:p-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-hive-md bg-hive-rose-soft text-hive-terracotta"><Lock size={20} /></div><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Account</p><h2 className="mt-1 text-2xl font-bold">Security & access</h2></div></div><div className="mt-7 space-y-3"><button type="button" onClick={() => setModal("password")} className="flex w-full items-center justify-between rounded-hive-lg border border-hive-border px-4 py-4 text-left transition hover:border-hive-terracotta"><span><span className="block font-semibold">Change password</span><span className="mt-1 block text-sm text-hive-muted">Update your sign-in password.</span></span><KeyRound className="text-hive-terracotta" size={18} /></button><button type="button" onClick={() => setModal("delete")} className="flex w-full items-center justify-between rounded-hive-lg border border-red-100 bg-red-50/50 px-4 py-4 text-left transition hover:bg-red-50"><span><span className="block font-semibold text-red-700">Delete account</span><span className="mt-1 block text-sm text-red-600/80">Placeholder — requires support verification.</span></span><Trash2 className="text-red-600" size={18} /></button></div></Card></section>
  </div><Modal isOpen={modal === "password"} onClose={() => setModal("")} title="Change password" description="Choose a new password with at least 8 characters."><div className="space-y-5"><Input label="Current password" type="password" value={password.current} onChange={(event) => setPassword({ ...password, current: event.target.value })} /><Input label="New password" type="password" hint="At least 8 characters." value={password.next} onChange={(event) => setPassword({ ...password, next: event.target.value })} /><div className="flex gap-3"><Button variant="outline" fullWidth onClick={() => setModal("")}>Cancel</Button><Button fullWidth onClick={changePassword}>Update password</Button></div></div></Modal><Modal isOpen={modal === "leave"} onClose={() => setModal("")} title="Leave Maple House?" description="You’ll lose access to household chores, plans, chat, and shared history."><div className="flex gap-3"><Button variant="outline" fullWidth onClick={() => setModal("")}>Stay in Hive</Button><Button fullWidth className="bg-red-600 hover:bg-red-700" onClick={() => { setModal(""); setNotice("Leave Hive is a UI-only confirmation until household membership is connected."); }}>Leave Hive</Button></div></Modal><Modal isOpen={modal === "delete"} onClose={() => setModal("")} title="Delete account" description="This is a placeholder. Account deletion will require backend verification and a recovery period before it can be completed."><Button fullWidth variant="outline" onClick={() => setModal("")}>I understand</Button></Modal></main>;
}

export default SettingsPage;
