import { Calendar, CheckCircle, Clock, Plus, Receipt, Users, Wallet } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge, Button, Card, Input, Modal } from "../../../components/ui";

const people = ["Aisha", "Sarah", "Mike", "Lena"];
const statusVariant = { "Due soon": "warning", "Partially paid": "accent", Settled: "success", "Awaiting shares": "neutral" };
const initialBills = [
  { id: 1, title: "Rent", category: "Rent", amount: 2400, due: "July 22", paidBy: "Not yet", status: "Due soon", owes: ["Aisha", "Sarah", "Mike", "Lena"] },
  { id: 2, title: "Hydro & water", category: "Utilities", amount: 154.8, due: "July 20", paidBy: "Sarah", status: "Partially paid", owes: ["Aisha", "Mike", "Lena"] },
  { id: 3, title: "Internet", category: "Internet", amount: 75, due: "July 18", paidBy: "Mike", status: "Settled", owes: [] },
  { id: 4, title: "House supplies", category: "Other", amount: 42.5, due: "July 28", paidBy: "Lena", status: "Awaiting shares", owes: ["Aisha", "Sarah", "Mike"] },
];

const money = (amount) => new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(amount);

function BillsPage() {
  const [isEnabled, setIsEnabled] = useState(true);
  const [bills, setBills] = useState(initialBills);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [form, setForm] = useState({ title: "", category: "Utilities", amount: "", due: "", paidBy: "Not yet", owes: [...people] });
  const summary = useMemo(() => ({ due: bills.filter((bill) => bill.status !== "Settled").reduce((total, bill) => total + bill.amount, 0), partial: bills.filter((bill) => bill.status === "Partially paid" || bill.status === "Awaiting shares").length, settled: bills.filter((bill) => bill.status === "Settled").length }), [bills]);
  const toggleOwes = (person) => setForm((current) => ({ ...current, owes: current.owes.includes(person) ? current.owes.filter((item) => item !== person) : [...current.owes, person] }));
  const addBill = () => { if (!form.title.trim() || !form.amount) return; const status = form.paidBy === "Not yet" ? "Due soon" : form.owes.length ? "Awaiting shares" : "Settled"; setBills((current) => [...current, { id: Date.now(), title: form.title, category: form.category, amount: Number(form.amount), due: form.due || "No due date", paidBy: form.paidBy, status, owes: form.owes }]); setIsModalOpen(false); };

  if (!isEnabled) return <main className="flex min-h-screen items-center justify-center bg-hive-canvas p-5"><Card className="w-full max-w-lg p-7 text-center sm:p-10"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-hive-lg bg-hive-rose-soft text-hive-terracotta"><Wallet size={25} /></div><h1 className="mt-6 text-3xl font-bold tracking-tight">Bills are turned off</h1><p className="mt-3 leading-7 text-hive-muted">Maple House can enable shared bill tracking anytime. Nothing else in HomeHive depends on it.</p><Button className="mt-8" size="lg" onClick={() => setIsEnabled(true)}>Enable bill tracking</Button></Card></main>;

  return <main className="min-h-screen bg-hive-canvas px-4 py-6 sm:px-6 lg:px-10 lg:py-10"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.16em] text-hive-terracotta"><Wallet size={16} /> Shared finances</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Household bills</h1><p className="mt-3 max-w-xl text-hive-muted">A calm, clear view of what&apos;s due and how the household is splitting it. No payments happen here.</p></div><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={() => setIsEnabled(false)}>Disable feature</Button><Button size="lg" onClick={() => setIsModalOpen(true)}><Plus size={18} /> Add bill</Button></div></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Still to sort</p><p className="mt-3 text-3xl font-bold">{money(summary.due)}</p><p className="mt-2 text-sm text-hive-muted">Across upcoming bills</p></Card><Card className="p-5"><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Awaiting shares</p><p className="mt-3 text-3xl font-bold text-[#a26a00]">{summary.partial}</p><p className="mt-2 text-sm text-hive-muted">Bills with a balance remaining</p></Card><Card className="p-5"><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Settled</p><p className="mt-3 text-3xl font-bold text-hive-sage">{summary.settled}</p><p className="mt-2 text-sm text-hive-muted">Bills fully shared this month</p></Card></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_20rem]"><div className="space-y-4">{bills.map((bill) => { const share = bill.owes.length ? bill.amount / (bill.owes.length + (bill.paidBy !== "Not yet" ? 1 : 0)) : 0; return <Card key={bill.id} className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-hive-md bg-hive-rose-soft text-hive-terracotta"><Receipt size={20} /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">{bill.title}</h2><Badge variant="neutral">{bill.category}</Badge><Badge variant={statusVariant[bill.status]}>{bill.status}</Badge></div><p className="mt-2 flex items-center gap-2 text-sm text-hive-muted"><Calendar size={15} /> Due {bill.due}</p></div></div><p className="text-2xl font-bold text-hive-ink">{money(bill.amount)}</p></div><div className="mt-5 grid gap-4 border-t border-hive-border pt-5 sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-hive-muted">Who paid</p><p className="mt-2 font-semibold">{bill.paidBy === "Not yet" ? "No payment recorded" : bill.paidBy}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-hive-muted">Who owes</p>{bill.owes.length ? <div className="mt-2 flex flex-wrap gap-2">{bill.owes.map((person) => <span key={person} className="rounded-full bg-hive-canvas px-2.5 py-1 text-sm font-semibold">{person}{share ? ` · ${money(share)}` : ""}</span>)}</div> : <p className="mt-2 flex items-center gap-2 font-semibold text-hive-sage"><CheckCircle size={16} /> Everyone is settled</p>}</div></div></Card>; })}</div>
      <aside className="space-y-5"><Card className="overflow-hidden bg-hive-ink-soft p-6 text-white"><div className="flex h-11 w-11 items-center justify-center rounded-hive-md bg-hive-honey text-hive-ink"><Users size={20} /></div><h2 className="mt-5 text-2xl font-bold">Money conversations, softened.</h2><p className="mt-3 leading-7 text-white/65">Bills make the shared numbers visible. Payment processing stays outside HomeHive for now.</p><div className="mt-6 border-t border-white/10 pt-5 text-sm text-white/65"><p className="flex items-center gap-2"><Clock size={16} className="text-hive-honey" /> Rent reminder in 4 days</p></div></Card><Card className="p-6"><p className="text-sm font-bold uppercase tracking-[0.14em] text-hive-terracotta">Status guide</p><div className="mt-5 space-y-3"><p className="flex items-center gap-2 text-sm"><Badge variant="warning">Due soon</Badge> No payment recorded</p><p className="flex items-center gap-2 text-sm"><Badge variant="accent">Partially paid</Badge> Some shares outstanding</p><p className="flex items-center gap-2 text-sm"><Badge variant="success">Settled</Badge> Everyone is square</p></div></Card></aside></section>
  </div><Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Add a household bill" description="This records a shared bill only; it will not collect a payment."><div className="space-y-5"><Input label="Bill title" placeholder="e.g. Gas bill" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold">Bill category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} className="mt-2 min-h-12 w-full rounded-hive-md border border-hive-border bg-hive-surface px-3 font-normal outline-none focus:border-hive-terracotta focus:ring-4 focus:ring-[var(--hh-focus-ring)]"><option>Rent</option><option>Utilities</option><option>Internet</option><option>Other</option></select></label><Input label="Amount (CAD)" type="number" min="0" step="0.01" placeholder="0.00" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></div><div className="grid gap-5 sm:grid-cols-2"><Input label="Due date" type="date" value={form.due} onChange={(event) => setForm({ ...form, due: event.target.value })} /><label className="block text-sm font-semibold">Who paid?<select value={form.paidBy} onChange={(event) => setForm({ ...form, paidBy: event.target.value })} className="mt-2 min-h-12 w-full rounded-hive-md border border-hive-border bg-hive-surface px-3 font-normal outline-none focus:border-hive-terracotta focus:ring-4 focus:ring-[var(--hh-focus-ring)]"><option>Not yet</option>{people.map((person) => <option key={person}>{person}</option>)}</select></label></div><div><p className="text-sm font-semibold">Who owes a share?</p><div className="mt-3 flex flex-wrap gap-2">{people.map((person) => <button key={person} type="button" onClick={() => toggleOwes(person)} className={`rounded-full px-3 py-2 text-sm font-semibold transition ${form.owes.includes(person) ? "bg-hive-terracotta text-white" : "bg-hive-canvas text-hive-muted hover:bg-hive-rose-soft"}`}>{person}</button>)}</div></div><div className="flex gap-3"><Button variant="outline" fullWidth onClick={() => setIsModalOpen(false)}>Cancel</Button><Button fullWidth onClick={addBill}><Plus size={17} /> Add bill</Button></div></div></Modal></main>;
}

export default BillsPage;
