import { Activity, CheckCircle, Clock, Gift, Mail, Sparkles, Trash2, Trophy, UserPlus, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge, Button, Card, Input, Modal } from "../../../components/ui";
import { getFriendlyName } from "../../../utils/userNames";

const roleVariant = { Owner: "accent", Admin: "warning", Member: "neutral" };
const initialMembers = [
  { id: 1, initials: "AM", name: "Aisha Martin", role: "Owner", tasks: 2, status: "Online", birthday: "December 8", contribution: 92, completed: 16, color: "bg-hive-terracotta" },
  { id: 2, initials: "SM", name: "Sarah Miller", role: "Admin", tasks: 1, status: "At home", birthday: "July 18", contribution: 88, completed: 14, color: "bg-hive-honey" },
  { id: 3, initials: "MJ", name: "Mike Jordan", role: "Member", tasks: 3, status: "Away", birthday: "March 2", contribution: 81, completed: 12, color: "bg-hive-sage" },
  { id: 4, initials: "LO", name: "Lena Ortiz", role: "Member", tasks: 1, status: "Online", birthday: "October 25", contribution: 95, completed: 18, color: "bg-[#8d77a8]" },
];

function MembersPage() {
  const [members, setMembers] = useState(initialMembers);
  const [isInviteOpen, setIsInviteOpen] = useState(false);
  const [memberToRemove, setMemberToRemove] = useState(null);
  const [invite, setInvite] = useState({ name: "", email: "", role: "Member" });
  const [notice, setNotice] = useState("");
  const averageContribution = useMemo(() => Math.round(members.reduce((total, member) => total + member.contribution, 0) / members.length), [members]);
  const topContributor = useMemo(() => members.reduce((top, member) => member.contribution > top.contribution ? member : top, members[0]), [members]);

  const changeRole = (id, role) => { setMembers((current) => current.map((member) => member.id === id ? { ...member, role } : member)); setNotice("Member role updated."); };
  const sendInvite = () => {
    if (!invite.name.trim() || !invite.email.includes("@")) return;
    const initials = invite.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
    setMembers((current) => [...current, { id: Date.now(), initials, name: invite.name, role: invite.role, tasks: 0, status: "Invite sent", birthday: "Add later", contribution: 0, completed: 0, color: "bg-[#8d77a8]" }]);
    setInvite({ name: "", email: "", role: "Member" }); setIsInviteOpen(false); setNotice(`Invite sent to ${invite.email}.`);
  };
  const removeMember = () => { setMembers((current) => current.filter((member) => member.id !== memberToRemove.id)); setNotice(`${memberToRemove.name} was removed from Maple House.`); setMemberToRemove(null); };

  return (
    <main className="min-h-screen bg-hive-canvas px-4 py-6 sm:px-6 lg:px-10 lg:py-10"><div className="mx-auto max-w-7xl">
      <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.16em] text-hive-terracotta"><Users size={16} /> Maple House</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Hive members</h1><p className="mt-3 max-w-xl text-hive-muted">The people who make your household feel like home.</p></div><Button size="lg" onClick={() => setIsInviteOpen(true)}><UserPlus size={18} /> Invite member</Button></header>
      {notice && <div className="mt-6 flex items-center justify-between gap-3 rounded-hive-md bg-hive-sage-soft px-4 py-3 text-sm text-hive-sage"><span>{notice}</span><button type="button" onClick={() => setNotice("")} className="font-bold">Dismiss</button></div>}

      <section className="mt-7 grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><Card className="overflow-hidden bg-hive-ink-soft p-6 text-white sm:p-8"><div className="flex items-start justify-between gap-4"><div><Badge variant="warning">Contribution insights</Badge><h2 className="mt-5 text-3xl font-bold">{averageContribution}% shared effort</h2><p className="mt-2 max-w-lg leading-7 text-white/65">Maple House is showing up for one another. Contribution blends completed chores, shared plans, and timely follow-through.</p></div><div className="flex h-12 w-12 items-center justify-center rounded-hive-lg bg-hive-honey text-hive-ink"><Activity size={22} /></div></div><div className="mt-8 h-3 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-hive-honey transition-all duration-500" style={{ width: `${averageContribution}%` }} /></div><div className="mt-4 flex flex-wrap justify-between gap-3 text-sm text-white/60"><span>{members.reduce((total, member) => total + member.completed, 0)} household tasks completed</span><span>{members.length} people contributing</span></div></Card><Card className="p-6 sm:p-8"><div className="flex h-11 w-11 items-center justify-center rounded-hive-md bg-hive-sage-soft text-hive-sage"><Trophy size={21} /></div><p className="mt-5 text-sm font-bold uppercase tracking-[0.16em] text-hive-terracotta">This month&apos;s bright spot</p><h2 className="mt-2 text-2xl font-bold">{getFriendlyName(topContributor)}</h2><p className="mt-2 leading-7 text-hive-muted">{topContributor.completed} completed contributions and a {topContributor.contribution}% household rhythm score.</p><Badge variant="success" className="mt-5">Consistency champion</Badge></Card></section>

      <section className="mt-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-hive-terracotta">Your household</p><h2 className="mt-2 text-2xl font-bold">Everyone in the Hive</h2></div><Badge variant="neutral">{members.length} members</Badge></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{members.map((member) => <Card key={member.id} interactive className="p-6"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className={`flex h-12 w-12 items-center justify-center rounded-full text-sm font-bold text-white ${member.color}`}>{member.initials}</div><div><h3 className="font-bold">{getFriendlyName(member)}</h3><p className="mt-1 text-sm text-hive-muted"><span className={`mr-1 inline-block h-2 w-2 rounded-full ${member.status === "Away" ? "bg-hive-honey" : member.status === "Invite sent" ? "bg-hive-terracotta" : "bg-hive-sage"}`} />{member.status}</p></div></div><Badge variant={roleVariant[member.role]}>{member.role}</Badge></div><div className="mt-6 grid grid-cols-2 gap-3 rounded-hive-lg bg-hive-canvas p-4"><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-hive-muted">Current tasks</p><p className="mt-2 text-2xl font-bold">{member.tasks}</p></div><div><p className="text-xs font-bold uppercase tracking-[0.1em] text-hive-muted">Contribution</p><p className="mt-2 text-2xl font-bold text-hive-sage">{member.contribution}%</p></div></div><div className="mt-5 space-y-3 text-sm"><p className="flex items-center gap-2 text-hive-muted"><Gift size={16} className="text-hive-terracotta" /><span>Birthday: <strong className="text-hive-ink">{member.birthday}</strong></span></p><p className="flex items-center gap-2 text-hive-muted"><CheckCircle size={16} className="text-hive-sage" /><span>{member.completed} completed household contributions</span></p></div><div className="mt-6 flex gap-2 border-t border-hive-border pt-5"><label className="min-w-0 flex-1"><span className="sr-only">Change {member.name}&apos;s role</span><select disabled={member.role === "Owner"} value={member.role} onChange={(event) => changeRole(member.id, event.target.value)} className="min-h-10 w-full rounded-hive-sm border border-hive-border bg-hive-surface px-3 text-sm font-semibold outline-none disabled:cursor-not-allowed disabled:opacity-60 focus:border-hive-terracotta focus:ring-4 focus:ring-[var(--hh-focus-ring)]"><option>Owner</option><option>Admin</option><option>Member</option></select></label>{member.role !== "Owner" && <button type="button" aria-label={`Remove ${member.name}`} onClick={() => setMemberToRemove(member)} className="rounded-hive-sm border border-hive-border p-2 text-hive-muted transition hover:border-red-300 hover:bg-red-50 hover:text-red-600"><Trash2 size={17} /></button>}</div></Card>)}</div></section>

      <section className="mt-5"><Card className="p-6 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-hive-terracotta">Household balance</p><h2 className="mt-2 text-2xl font-bold">A fairer share for everyone</h2></div><Sparkles className="text-hive-terracotta" /></div><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{members.map((member) => <div key={member.id} className="rounded-hive-lg bg-hive-canvas p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{getFriendlyName(member)}</p><span className="text-sm font-bold text-hive-sage">{member.contribution}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-hive-rose-soft"><div className="h-full rounded-full bg-hive-sage" style={{ width: `${member.contribution}%` }} /></div><p className="mt-3 flex items-center gap-2 text-sm text-hive-muted"><Clock size={14} /> {member.tasks} active tasks</p></div>)}</div></Card></section>
    </div>
    <Modal isOpen={isInviteOpen} onClose={() => setIsInviteOpen(false)} title="Invite someone home" description="Add a roommate, family member, or partner to Maple House."><div className="space-y-5"><Input label="Name" placeholder="Jordan Lee" value={invite.name} onChange={(event) => setInvite({ ...invite, name: event.target.value })} /><Input label="Email address" type="email" placeholder="jordan@example.com" value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })} /><label className="block text-sm font-semibold">Starting role<select value={invite.role} onChange={(event) => setInvite({ ...invite, role: event.target.value })} className="mt-2 min-h-12 w-full rounded-hive-md border border-hive-border bg-hive-surface px-3 font-normal outline-none focus:border-hive-terracotta focus:ring-4 focus:ring-[var(--hh-focus-ring)]"><option>Member</option><option>Admin</option></select></label><div className="flex gap-3"><Button variant="outline" fullWidth onClick={() => setIsInviteOpen(false)}>Cancel</Button><Button fullWidth onClick={sendInvite}><Mail size={17} /> Send invite</Button></div></div></Modal>
    <Modal isOpen={Boolean(memberToRemove)} onClose={() => setMemberToRemove(null)} title="Remove member?" description={`Remove ${memberToRemove?.name ?? "this member"} from Maple House? They will no longer have access to shared household information.`}><div className="flex gap-3"><Button variant="outline" fullWidth onClick={() => setMemberToRemove(null)}>Keep member</Button><Button fullWidth className="bg-red-600 hover:bg-red-700" onClick={removeMember}><Trash2 size={17} /> Remove</Button></div></Modal>
    </main>
  );
}

export default MembersPage;
